### ISSUE TITLE
Parameter for clearing output directory

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojpch-performance-test#2]
Can we have a parameter that clears the output directory before starting.

Pls also check in ojp-nova for the code that makes sure a directory exists (and if not creates it) before starting. Otherwise we have to create the directory manually.

**Comment by markus-meier-sbb** [comment]
Done in commit https://github.com/openTdataCH/ojpch-performance-test/commit/7a20826ae13a5d91da2ee3c8c864366a11927193
