### ISSUE TITLE
Wird bräuchten auch einen Test mit TRIAS2020

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojpch-performance-test#4]
* endpoint: https://api.opentransportdata.swiss/trias2020
* Schlüssel wie für OJP PROD
* Primär TripRequest

Beispiel: siehe API Explorer: https://opentransportdata.swiss/de/cookbook/triprequest/?highlight=TRIAS

**Comment by markus-meier-sbb** [comment]
Done in commit https://github.com/openTdataCH/ojpch-performance-test/commit/7a20826ae13a5d91da2ee3c8c864366a11927193
