### ISSUE TITLE
Error occured in TIR

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojpch-performance-test#6]
Error
`2023-10-24 23:52:30,151: INFO: -  ... prior TR for TIR: Meilen, Obermei -> ZÃ¼rich, Farbho, calc. time 0.021 ms, 429 Too Many Requests, opday=None, jr=None.
2023-10-24 23:52:30,151: INFO: -  ... op_day_ref and/or journey_ref are invalid - repeat.
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test\ojp_performance_tests.py", line 381, in <module>
    process()
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test\ojp_performance_tests.py", line 376, in process
    test_run(test_directory, environment, request_type, statistics)
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test\ojp_performance_tests.py", line 331, in test_run
    t = send_request(env, request_type, results_table, session, test_directory, i + 1)
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test\ojp_performance_tests.py", line 289, in send_request
    response, calc_time = http_post(session, env, body)
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test\ojp_performance_tests.py", line 273, in http_post
    body=body.encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'

Process finished with exit code 1
`

With this parameter set:
`# Parameter File for configuring parameters of a test run.
# 'parameters.txt' is the default file.
# Another file in 'input' directory may be used instead. Provide the file name as command line argument.

# BASE TEST SETUP
# number of requests (tests) to perform on each environment
number_of_requests = 200

# environments to test; comma-separated list.
# environments = PROD, INT, TEST, LA_BETA, LINUX_TEST, LINUX_INT
environments = PROD

# Type of OJP request: TR, LIR, SER, TIR; comma-separated list.
request_types = TR, LIR, SER, TIR

# For TR and SER only: use "Geo position" (coordinates) rather than "Stop Place Ref" (didok stops)?
use_geopos = False
# If yes, add a random offset with a given max_dist_from_stop (in kilometers)
max_dist_from_stop = 0.5

# PARAMETERS INFLUENCING PERFORMANCE:
# use a session for http requests?
use_session = True

# save all details, including requests/responses, to file
save_details = True

# settings for the random number generator; if a "seed" is used, the test run will have same stations in repetition:
use_random_seed = True
random_seed = 42

# time in seconds to wait before sending the next request
sleep_time = 0.1

# DEPARTURE DATE/TIME SETTINGS:
# define ranges for the depature date (days ahead of today) and time of the day:
days_ahead_min = 1
days_ahead_max = 1
hours_min = 7
hours_max = 10
minutes_min = 0
minutes_max = 59

# OJP PARAMETERS / RESTRICTIONS SECTION:
# "MAIN SWITCH": Use some extra parameters at all?
use_params = False

# OJP TR parameters:
tr_include_track_sections = True
tr_include_leg_projection = True
tr_include_turn_description = True
tr_include_intermediate_stops = True
# do not use location name in OJP TR, use "ORIGIN" or "DESTINATION" instead:
mask_location_name = True

# OJP SER parameters:
ser_number_of_results = 10
ser_stop_event_type_reference = departure
ser_operator_exclude = True
ser_operator_ref = unknown
ser_include_previous_calls = True
ser_include_onward_calls = True
ser_include_realtime_cata = True

# OJP LIR RESTRICTIONS
# one of these: stop, address, poi, coord, topographicPlace:
lir_geo_restriction_type = stop
lir_number_of_results = 10
lir_include_pt_modes = True

# OJP TIR PARAMETERS:
tir_include_calls = True
tir_include_track_sections = True
tir_include_service = True

# MISCELLANEOUS
# download DIDOK stations/stops from opentransportdata.swiss
download_didok_data = False
`

**Comment by ue71603** [comment]
If you edit the description it is easier to copy&paste the configuration

**Comment by markus-meier-sbb** [comment]
Fixed in commit https://github.com/openTdataCH/ojpch-performance-test/commit/7a20826ae13a5d91da2ee3c8c864366a11927193
